spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:4dm1n@cluster0.genjgr0.mongodb.net/hrms?retryWrites=true&w=majority&appName=Cluster0

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG

jwt:
  utils:
    key: eD7nH9JHgX1Q2YqVrZG3f7qPp0V57D1jE9vNjT2j2Y8=
    expiration: 120000
