package com.mongodb.api.hrms.mapper;

import com.mongodb.api.hrms.dto.LeaveDto;
import com.mongodb.api.hrms.model.Leave;
import com.mongodb.api.hrms.utils.TestDataUtils;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

import static org.junit.jupiter.api.Assertions.assertEquals;

// Use Spring's test context with a specific configuration class
@SpringJUnitConfig(LeaveMapperTest.Config.class)
class LeaveMapperTest {
    // Configuration class that tells Spring to scan for components in the same package as LeaveMapper. This allows
    // Spring to detect and instantiate the mapper.
    @Configuration
    @ComponentScan(basePackageClasses = LeaveMapper.class)
    static class Config {
        // No beans manually defined here — we rely on component scanning.
    }

    // Spring will inject the mapper implementation generated by MapStruct
    @Autowired
    LeaveMapper leaveMapper;

    @Test
    void leaveDtoToLeave() {
        String id = "68294342f43b2332e73fbb07";

        LeaveDto source = TestDataUtils.createFullyPopulatedLeaveDto(id);
        Leave target = TestDataUtils.createFullyPopulatedLeave(id);

        Leave result = leaveMapper.leaveDtoToLeave(source);

        assertEquals(target, result);
    }

    @Test
    void leaveToLeaveDto() {
        String id = "68294342f43b2332e73fbb07";

        Leave source = TestDataUtils.createFullyPopulatedLeave(id);
        LeaveDto target = TestDataUtils.createFullyPopulatedLeaveDto(id);

        LeaveDto result = leaveMapper.leaveToLeaveDto(source);

        assertEquals(target, result);
    }
}
